provider: ollama  # 或 'openai'
model: llama3.1  # 或者对于 OpenAI 可以是 'gpt-3.5-turbo'
api_key: your_api_key_here  # 对于 Ollama 可以省略
system_prompt: "You are a helpful assistant."
temperature: 0.7
max_tokens: 1000