# openai_config.yaml

# The API key will be loaded from an environment variable
api_key: "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"

# The model to use (e.g., "gpt-3.5-turbo", "gpt-4")
model: "gpt-3.5-turbo"

# Generation parameters
generation_params:
  temperature: 0.7
  max_tokens: 1500
  top_p: 1.0
  frequency_penalty: 0.0
  presence_penalty: 0.0